### ISSUE TITLE
[Bug]: Illogical pipe DN results by growth optimizer

### ISSUE THREAD

**Issue by JurrianVRHDHV** [Project-OMOTES/user_feedback#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

The results of growth optimizing the network: "DelftV2.2_(DummyPiek)" shows a pipe section where a DN450 diameter pipe is place placed between DN400 pipe sections.
So starting at the producer: 

- Generic producer (WPC) -> Pipe6 (DN400) -> Pipe7 (DN400) -> Pipe9 (DN400) -> Pipe14 (DN400) -> **Pipe15 (DN450)** -> Pipe17 (DN400) -> etc...
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/0a917df9-ee1f-470b-aabc-b2edfa5c2531)

Logic would see the pipe diameter getting gradually smaller, when following the flow direction.
So the reason that pipe 15 has a larger diameter, than pipes 6, 7, 9 & 14 is unclear.

The grow optimization showed to have been succesfull.

### Steps to reproduce the problem

Ive added both the original, with return network and grow optimized file.

1. Open the file "Base Netwerk Delft_V2.2_(DummyPiek) with return network_GrowOptimized_False Positive.esdl" in the map editor
2. Check Pipe15 to verify the issue (*note ZIP-file also includes logfile) OR use the file "Base Netwerk Delft_V2.2_(DummyPiek) with return network.esdl" and repeat the grow optimization.

[Delft_V2.2_(DummyPiek).zip](https://github.com/Project-OMOTES/user_feedback/files/15218298/Delft_V2.2_.DummyPiek.zip)

### What should have happened?

The pipe (pipe15) should have a "seemingly logical" DN400 OR the previous pipe section between the producer and "illogical pipe" should be DN450.
That would fit with a "normal" gradual decrease in pipe diameter when following the flow direction.

### What browsers do you use to access the UI?

Mozilla Firefox

**Comment by KobusVanRooyen** [comment]
- I have seen this network before via Jan. I tried to look at the network again, but the zip file is empty. @JurrianVRHDHV  can you please upload the data again. Please also upload the log file. I can double check some items.  
- In which environment was this network solved? I assume it was done in the PoC (https://nwn-design-toolkit-poc.nl/)? If this is true then certain error checks were not done when running this case.
- If the PoC was used to optimize this network, then there is the potential for the optimizer could return an invalid result due to invalid input data. Invalid input data: make sure the heating demand installed capacity > maximum peak demand expected, ensure the specified producing capacity is large enough, ensure the pipe DN is size specified as optional is large enough to cater for the expected max demand
- Example of invalid input data. Check demand "TRA07_Rotterdamseweg 139", the installed capacity is 0.48MW but the expected maximum demand is 1.81MW (max in the profile specified) * 0.3(multplier) = 0.543MW. In the PoC environment this would have ended up in an invalid end result, that would explain the weird result. In the new MWP environment this would have created an error and no result should be given.

**Comment by KobusVanRooyen** [comment]
Awaiting feedback

**Comment by JurrianVRHDHV** [comment]
2nd attempt to upload the zipfile.
[Delft_V2.2_(DummyPiek).zip](https://github.com/user-attachments/files/15783570/Delft_V2.2_.DummyPiek.zip)

- I have so far been running it in the PoC environment.
- I included a secondary producer with ample capacity (100MW, but a higher cost/MW), which was not used in the optimization (see the base- and return network versions) and the DN size of the optional pipes is set to DN700, which should be more than enough for this network.
- The invalid input data was a result of a rounding error. 480kW resulted in 0.265 (which was rounded up to 0.3) as I did not know the accuracy that was expected. What would you suggest as the level of accuracy (how many decimal points) to prevent any future errors?

Please document all corrected errors you identify (such as the invalid expected maximum demand) so that I can adjust them in the "spinn-offs" network we have continued with. Our goal it to use V2.2 as a baseline for the case network which can run without errors and create plausible results.

**Comment by samvanderzwan** [comment]
@JurrianVRHDHV  us this still active?

**Comment by JurrianVRHDHV** [comment]
@samvanderzwan, the issue has been resolved as far as possible with the help of @KobusVanRooyen.
This specific issue was identified to be a false-positive output of the optimizer, in combination with some unvalidated errors with the accuracy of the input.
