### ISSUE TITLE
[Bug]: ESDL is not loaded after optimisation run has finished

### ISSUE THREAD

**Issue by samvanderzwan** [Project-OMOTES/user_feedback#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

I have run an optimisation with the attached model. But Map editor becomes stuck when I try to load the results.

### Steps to reproduce the problem

1. load ESDL into mapedtior
2. service -> external services  -> Start heat network calculation
3. Select Grow optimisation and run, then wait for the result
4. Load result then mapeditor freezes.

Some investigation showed that for the kpi estimation percentage local is nan.

### What should have happened?

Results shoudl have been loaded into mapeditor or an error should be given why the results are not loaded.

### What browsers do you use to access the UI?

Mozilla Firefox

### Additional information

I added the original and optimized ESDL.
Furthermore I found the following:
If I remove the kpi parts then it can be loaded into mapeditor. However the result is not as expected. Only one heatdemand is connect and the rest is disconnected. This is proably due to the fact that the supply is not sufficient, but at this moment the user is not informed on this.
Setting the multiplier of all heat demands to 1 gives results which are loaded into map editor
[RWZI Den Bosch test 21-5 - incl kosten leidingnet update pipe-teo optional.esdl.txt](https://github.com/Project-OMOTES/user_feedback/files/15434005/RWZI.Den.Bosch.test.21-5.-.incl.kosten.leidingnet.update.pipe-teo.optional.esdl.txt)
[Untitled EnergySystem with return network_GrowOptimized.esdl.txt](https://github.com/Project-OMOTES/user_feedback/files/15434040/Untitled.EnergySystem.with.return.network_GrowOptimized.esdl.txt)

**Comment by KobusVanRooyen** [comment]
@samvanderzwan  I will also check newer version (MVP and not the PoC version)

**Comment by KobusVanRooyen** [comment]
@samvanderzwan here is my feedback:
- I used the original network drawn, and then I used the duplicator in the PoC environment to create the return pipe network
- I did not make any other changes to the input settings before trying to optimize the network
- I ran the MVP version 0.1.3.1 of MESIDO locally, as the PoC version is outdated. Secondly there are some new error checks in this version of MESIDO which does not exist in the PoC version of the optmizer.
- An error is displayed by MESIDO: "ERROR The heating demand is not matched". 
- There are several issues in the network input settings:
1. The heating demands installed capacities (used as the upper limit of possible demand value) are not sufficient. This value must be larger than the maximum demand that will occur. Example demand="HeatingDemand_da5b" has a installed power=0.13067MW. The demand profile used is ..._demand3_MW which has a peak value of about 0.8MW combined with a multiplier value of 5 means that this demand will have a peak demand value of 0.8*5 = 4MW. This cannot work and it has been explained since the 1st PoC tutorial. I changed the installed capacity of each heating demand to 8MW, to make sure it is big enough. 
2. The installed capacity is not large enough. If I estimate the total peak demand (by looking at the profiles and the multipliers) it seems that a installed capacity > 4*4MW = 16MW is required without taking into account heat losses. The current installed capacity in the network is TEO_Maas=1MW and TEA_Rioolwaterzuivering=7.772957MW. This cannot work and it has been explained since the 1st PoC tutorial. I changed the installed capacity of each producers to 15M each, to make sure there is enough heat producing capacity.
3. Also did a check on the pipe DN since the network has a dT = 6. A safe estimate of the total heat demand + losses = 20MW would require a main supply pipe of roughly 600mm. Currently the main pipes have been specified to have an upper limit of DN600 which might not be enough. I changed these pipes to DN700 to make sure they are large enough.
- After these changes were made the network was able to be optimized

**Comment by KobusVanRooyen** [comment]
This issue is therefore not a bug. Please change the label and close the issue.

**Comment by KobusVanRooyen** [comment]
@samvanderzwan can you please close this item. If not closed, please give me feedback on this item.

**Comment by samvanderzwan** [comment]
First two points Ok, if the users gets feedback that this is the case.
third point I am a little in doubt, why choose this upper limit, how is the user informed that an upper limit is used?
